// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: pii/v1/ner.proto

package piiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Text  string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// language 是语言上下文，默认 "zh"。
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// entity_types 限定需要识别的类型。留空表示全部。
	//
	// 由调用方指定而不是让服务端全返回：前两层已经处理掉的类型不必再算，
	// 而模型对每个类型的开销是实打实的。
	//
	// Specified by the caller rather than returning everything: types the first
	// two layers already handled need not be computed.
	EntityTypes   []string `protobuf:"bytes,3,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_pii_v1_ner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pii_v1_ner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_pii_v1_ner_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnalyzeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AnalyzeRequest) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

type NEREntity struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EntityType string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	// start / end 是**字符**偏移（Unicode code point），不是字节偏移。
	//
	// 这是整套架构里最容易出错的一处，因此写在契约里而不是留给约定：
	// Python 的 str 按字符索引，Go 的 string 按字节索引，一个汉字占 3 字节。
	// 拿 Python 的 [2:4] 直接去切 Go 的字符串，切出来的是「你」字的一部分——
	// 敏感词没洗掉，报文还被切成了非法 UTF-8。
	//
	// Go 侧必须在收到响应后做 rune→byte 映射。text 字段的存在就是为了让
	// 这次映射可以被立即验证：映射后切出来的字节必须与 text 逐字相同。
	//
	// Character offsets (Unicode code points), not bytes. This is the single
	// most error-prone point in the architecture, so it is stated in the
	// contract rather than left to convention: Python indexes str by character,
	// Go indexes string by byte, and a Chinese character is three bytes. Slicing
	// Go's string with Python's [2:4] yields part of a character — the sensitive
	// value survives and the payload becomes invalid UTF-8.
	//
	// The Go side must map rune→byte on receipt. The text field exists so that
	// mapping can be verified immediately: the mapped bytes must equal it.
	Start int32 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int32 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	// text 是被识别出的文本原文。
	//
	// 它不只是给人看的：Go 侧用它来验证偏移映射是否正确。少了它，一次错位
	// 只会表现为「脱敏了错的几个字」，而没有任何东西能发现这件事。
	//
	// Not merely informational: the Go side verifies the offset mapping against
	// it. Without it, a misalignment shows up only as "the wrong characters were
	// redacted", which nothing detects.
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// score 是模型给出的置信度。
	//
	// 不是所有后端都有真实分数：spaCy 的默认 EntityRecognizer 不输出逐实体
	// 概率。服务端在没有真分数时应当返回一个明显恒定的值，而不是编一个
	// 像模像样的 0.95——下游按阈值判定时，看到所有实体分数完全相同
	// 就会立刻发现这件事。
	//
	// Not every backend has a real score. A backend without one should return a
	// visibly constant value rather than inventing a plausible 0.95.
	Score         float32 `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NEREntity) Reset() {
	*x = NEREntity{}
	mi := &file_pii_v1_ner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NEREntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NEREntity) ProtoMessage() {}

func (x *NEREntity) ProtoReflect() protoreflect.Message {
	mi := &file_pii_v1_ner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NEREntity.ProtoReflect.Descriptor instead.
func (*NEREntity) Descriptor() ([]byte, []int) {
	return file_pii_v1_ner_proto_rawDescGZIP(), []int{1}
}

func (x *NEREntity) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *NEREntity) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *NEREntity) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *NEREntity) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *NEREntity) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type AnalyzeResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Entities []*NEREntity           `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	// model 标识实际产出这批实体的后端，例如 "spacy:zh_core_web_md"。
	//
	// 审计需要知道这批判定是谁做的。换模型是一次会改变检出结果的变更，
	// 而没有这个字段时，那次变更在日志里不留痕迹。
	//
	// Audit needs to know which backend produced these. Swapping the model
	// changes what is detected, and without this field that change leaves no
	// trace in the logs.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// 服务端自报的推理耗时（微秒），用于把网络往返与模型耗时分开。
	// Server-side inference time, to separate round-trip from model cost.
	InferenceMicros int64 `protobuf:"varint,3,opt,name=inference_micros,json=inferenceMicros,proto3" json:"inference_micros,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_pii_v1_ner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pii_v1_ner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_pii_v1_ner_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeResponse) GetEntities() []*NEREntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *AnalyzeResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AnalyzeResponse) GetInferenceMicros() int64 {
	if x != nil {
		return x.InferenceMicros
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pii_v1_ner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pii_v1_ner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pii_v1_ner_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ready bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Model string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// supported_types 是本后端实际能产出的类型。
	//
	// 供 Go 侧做覆盖度自检：一个不产出 ORGANIZATION 的后端，配上一条要求
	// 脱敏机构名的策略，是一个静默的缺口。
	//
	// Lets the Go side check coverage: a backend that never emits ORGANIZATION,
	// paired with a policy that redacts organizations, is a silent gap.
	SupportedTypes []string `protobuf:"bytes,3,rep,name=supported_types,json=supportedTypes,proto3" json:"supported_types,omitempty"`
	Detail         string   `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pii_v1_ner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pii_v1_ner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pii_v1_ner_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HealthResponse) GetSupportedTypes() []string {
	if x != nil {
		return x.SupportedTypes
	}
	return nil
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_pii_v1_ner_proto protoreflect.FileDescriptor

const file_pii_v1_ner_proto_rawDesc = "" +
	"\n" +
	"\x10pii/v1/ner.proto\x12\x06pii.v1\"c\n" +
	"\x0eAnalyzeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12!\n" +
	"\fentity_types\x18\x03 \x03(\tR\ventityTypes\"~\n" +
	"\tNEREntity\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x05R\x03end\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\"\x81\x01\n" +
	"\x0fAnalyzeResponse\x12-\n" +
	"\bentities\x18\x01 \x03(\v2\x11.pii.v1.NEREntityR\bentities\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12)\n" +
	"\x10inference_micros\x18\x03 \x01(\x03R\x0finferenceMicros\"\x0f\n" +
	"\rHealthRequest\"}\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12'\n" +
	"\x0fsupported_types\x18\x03 \x03(\tR\x0esupportedTypes\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail2\x81\x01\n" +
	"\n" +
	"NERService\x12:\n" +
	"\aAnalyze\x12\x16.pii.v1.AnalyzeRequest\x1a\x17.pii.v1.AnalyzeResponse\x127\n" +
	"\x06Health\x12\x15.pii.v1.HealthRequest\x1a\x16.pii.v1.HealthResponseBJZHgithub.com/xinleishen84-afk/airlock-agent/nerclient/genproto/piiv1;piiv1b\x06proto3"

var (
	file_pii_v1_ner_proto_rawDescOnce sync.Once
	file_pii_v1_ner_proto_rawDescData []byte
)

func file_pii_v1_ner_proto_rawDescGZIP() []byte {
	file_pii_v1_ner_proto_rawDescOnce.Do(func() {
		file_pii_v1_ner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pii_v1_ner_proto_rawDesc), len(file_pii_v1_ner_proto_rawDesc)))
	})
	return file_pii_v1_ner_proto_rawDescData
}

var file_pii_v1_ner_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pii_v1_ner_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: pii.v1.AnalyzeRequest
	(*NEREntity)(nil),       // 1: pii.v1.NEREntity
	(*AnalyzeResponse)(nil), // 2: pii.v1.AnalyzeResponse
	(*HealthRequest)(nil),   // 3: pii.v1.HealthRequest
	(*HealthResponse)(nil),  // 4: pii.v1.HealthResponse
}
var file_pii_v1_ner_proto_depIdxs = []int32{
	1, // 0: pii.v1.AnalyzeResponse.entities:type_name -> pii.v1.NEREntity
	0, // 1: pii.v1.NERService.Analyze:input_type -> pii.v1.AnalyzeRequest
	3, // 2: pii.v1.NERService.Health:input_type -> pii.v1.HealthRequest
	2, // 3: pii.v1.NERService.Analyze:output_type -> pii.v1.AnalyzeResponse
	4, // 4: pii.v1.NERService.Health:output_type -> pii.v1.HealthResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pii_v1_ner_proto_init() }
func file_pii_v1_ner_proto_init() {
	if File_pii_v1_ner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pii_v1_ner_proto_rawDesc), len(file_pii_v1_ner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pii_v1_ner_proto_goTypes,
		DependencyIndexes: file_pii_v1_ner_proto_depIdxs,
		MessageInfos:      file_pii_v1_ner_proto_msgTypes,
	}.Build()
	File_pii_v1_ner_proto = out.File
	file_pii_v1_ner_proto_goTypes = nil
	file_pii_v1_ner_proto_depIdxs = nil
}
