// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: pii/v1/ner.proto

package piiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NERService_Analyze_FullMethodName = "/pii.v1.NERService/Analyze"
	NERService_Health_FullMethodName  = "/pii.v1.NERService/Health"
)

// NERServiceClient is the client API for NERService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NERService 是 Go 网关与 Python 推理进程之间的唯一契约。
//
// NERService is the only contract between the Go gateway and the Python
// inference process.
//
// # 为什么是 gRPC over UDS
// # Why gRPC over a Unix domain socket
//
// 这条调用在 TTFT 关键路径上：每个未命中前两层的请求都要等它。走本地
// TCP 环回要经过完整的协议栈——三次握手、Nagle、内核收发缓冲、校验和——
// 而这些对同机进程间通信没有任何价值。UDS 绕过整个网络栈，只做一次
// 内核内存拷贝。
//
// This call sits on the TTFT critical path. Local TCP loopback pays for the
// full stack — handshake, Nagle, socket buffers, checksums — none of which
// buys anything between two processes on one machine. A Unix domain socket
// skips the network stack entirely.
type NERServiceClient interface {
	// Analyze 对一段文本做实体识别。
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
	// Health 供 Go 侧在启动期确认模型已加载。
	//
	// 分开一个方法而不是靠 Analyze 探活：模型加载失败时 Analyze 也会失败，
	// 但那时候第一个真实请求已经进来了。启动期就该知道。
	//
	// A separate method rather than probing with Analyze: a failed model load
	// makes Analyze fail too, but by then the first real request has arrived.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type nERServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNERServiceClient(cc grpc.ClientConnInterface) NERServiceClient {
	return &nERServiceClient{cc}
}

func (c *nERServiceClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, NERService_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nERServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, NERService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NERServiceServer is the server API for NERService service.
// All implementations must embed UnimplementedNERServiceServer
// for forward compatibility.
//
// NERService 是 Go 网关与 Python 推理进程之间的唯一契约。
//
// NERService is the only contract between the Go gateway and the Python
// inference process.
//
// # 为什么是 gRPC over UDS
// # Why gRPC over a Unix domain socket
//
// 这条调用在 TTFT 关键路径上：每个未命中前两层的请求都要等它。走本地
// TCP 环回要经过完整的协议栈——三次握手、Nagle、内核收发缓冲、校验和——
// 而这些对同机进程间通信没有任何价值。UDS 绕过整个网络栈，只做一次
// 内核内存拷贝。
//
// This call sits on the TTFT critical path. Local TCP loopback pays for the
// full stack — handshake, Nagle, socket buffers, checksums — none of which
// buys anything between two processes on one machine. A Unix domain socket
// skips the network stack entirely.
type NERServiceServer interface {
	// Analyze 对一段文本做实体识别。
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	// Health 供 Go 侧在启动期确认模型已加载。
	//
	// 分开一个方法而不是靠 Analyze 探活：模型加载失败时 Analyze 也会失败，
	// 但那时候第一个真实请求已经进来了。启动期就该知道。
	//
	// A separate method rather than probing with Analyze: a failed model load
	// makes Analyze fail too, but by then the first real request has arrived.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedNERServiceServer()
}

// UnimplementedNERServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNERServiceServer struct{}

func (UnimplementedNERServiceServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedNERServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedNERServiceServer) mustEmbedUnimplementedNERServiceServer() {}
func (UnimplementedNERServiceServer) testEmbeddedByValue()                    {}

// UnsafeNERServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NERServiceServer will
// result in compilation errors.
type UnsafeNERServiceServer interface {
	mustEmbedUnimplementedNERServiceServer()
}

func RegisterNERServiceServer(s grpc.ServiceRegistrar, srv NERServiceServer) {
	// If the following call panics, it indicates UnimplementedNERServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NERService_ServiceDesc, srv)
}

func _NERService_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NERServiceServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NERService_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NERServiceServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NERService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NERServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NERService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NERServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NERService_ServiceDesc is the grpc.ServiceDesc for NERService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NERService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pii.v1.NERService",
	HandlerType: (*NERServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _NERService_Analyze_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _NERService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pii/v1/ner.proto",
}
