# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pii/v1/ner.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pii/v1/ner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pii/v1/ner.proto\x12\x06pii.v1\"F\n\x0e\x41nalyzeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x14\n\x0c\x65ntity_types\x18\x03 \x03(\t\"Y\n\tNEREntity\x12\x13\n\x0b\x65ntity_type\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\r\n\x05score\x18\x05 \x01(\x02\"_\n\x0f\x41nalyzeResponse\x12#\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x11.pii.v1.NEREntity\x12\r\n\x05model\x18\x02 \x01(\t\x12\x18\n\x10inference_micros\x18\x03 \x01(\x03\"\x0f\n\rHealthRequest\"W\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\r\n\x05model\x18\x02 \x01(\t\x12\x17\n\x0fsupported_types\x18\x03 \x03(\t\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t2\x81\x01\n\nNERService\x12:\n\x07\x41nalyze\x12\x16.pii.v1.AnalyzeRequest\x1a\x17.pii.v1.AnalyzeResponse\x12\x37\n\x06Health\x12\x15.pii.v1.HealthRequest\x1a\x16.pii.v1.HealthResponseBJZHgithub.com/xinleishen84-afk/airlock-agent/nerclient/genproto/piiv1;piiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pii.v1.ner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZHgithub.com/xinleishen84-afk/airlock-agent/nerclient/genproto/piiv1;piiv1'
  _globals['_ANALYZEREQUEST']._serialized_start=28
  _globals['_ANALYZEREQUEST']._serialized_end=98
  _globals['_NERENTITY']._serialized_start=100
  _globals['_NERENTITY']._serialized_end=189
  _globals['_ANALYZERESPONSE']._serialized_start=191
  _globals['_ANALYZERESPONSE']._serialized_end=286
  _globals['_HEALTHREQUEST']._serialized_start=288
  _globals['_HEALTHREQUEST']._serialized_end=303
  _globals['_HEALTHRESPONSE']._serialized_start=305
  _globals['_HEALTHRESPONSE']._serialized_end=392
  _globals['_NERSERVICE']._serialized_start=395
  _globals['_NERSERVICE']._serialized_end=524
# @@protoc_insertion_point(module_scope)
