# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from pii.service.genproto.pii.v1 import ner_pb2 as pii_dot_v1_dot_ner__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pii/v1/ner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NERServiceStub:
    """NERService 是 Go 网关与 Python 推理进程之间的唯一契约。

    NERService is the only contract between the Go gateway and the Python
    inference process.

    # 为什么是 gRPC over UDS
    # Why gRPC over a Unix domain socket

    这条调用在 TTFT 关键路径上：每个未命中前两层的请求都要等它。走本地
    TCP 环回要经过完整的协议栈——三次握手、Nagle、内核收发缓冲、校验和——
    而这些对同机进程间通信没有任何价值。UDS 绕过整个网络栈，只做一次
    内核内存拷贝。

    This call sits on the TTFT critical path. Local TCP loopback pays for the
    full stack — handshake, Nagle, socket buffers, checksums — none of which
    buys anything between two processes on one machine. A Unix domain socket
    skips the network stack entirely.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/pii.v1.NERService/Analyze',
                request_serializer=pii_dot_v1_dot_ner__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=pii_dot_v1_dot_ner__pb2.AnalyzeResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/pii.v1.NERService/Health',
                request_serializer=pii_dot_v1_dot_ner__pb2.HealthRequest.SerializeToString,
                response_deserializer=pii_dot_v1_dot_ner__pb2.HealthResponse.FromString,
                _registered_method=True)


class NERServiceServicer:
    """NERService 是 Go 网关与 Python 推理进程之间的唯一契约。

    NERService is the only contract between the Go gateway and the Python
    inference process.

    # 为什么是 gRPC over UDS
    # Why gRPC over a Unix domain socket

    这条调用在 TTFT 关键路径上：每个未命中前两层的请求都要等它。走本地
    TCP 环回要经过完整的协议栈——三次握手、Nagle、内核收发缓冲、校验和——
    而这些对同机进程间通信没有任何价值。UDS 绕过整个网络栈，只做一次
    内核内存拷贝。

    This call sits on the TTFT critical path. Local TCP loopback pays for the
    full stack — handshake, Nagle, socket buffers, checksums — none of which
    buys anything between two processes on one machine. A Unix domain socket
    skips the network stack entirely.
    """

    def Analyze(self, request, context):
        """Analyze 对一段文本做实体识别。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health 供 Go 侧在启动期确认模型已加载。

        分开一个方法而不是靠 Analyze 探活：模型加载失败时 Analyze 也会失败，
        但那时候第一个真实请求已经进来了。启动期就该知道。

        A separate method rather than probing with Analyze: a failed model load
        makes Analyze fail too, but by then the first real request has arrived.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NERServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=pii_dot_v1_dot_ner__pb2.AnalyzeRequest.FromString,
                    response_serializer=pii_dot_v1_dot_ner__pb2.AnalyzeResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=pii_dot_v1_dot_ner__pb2.HealthRequest.FromString,
                    response_serializer=pii_dot_v1_dot_ner__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pii.v1.NERService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pii.v1.NERService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NERService:
    """NERService 是 Go 网关与 Python 推理进程之间的唯一契约。

    NERService is the only contract between the Go gateway and the Python
    inference process.

    # 为什么是 gRPC over UDS
    # Why gRPC over a Unix domain socket

    这条调用在 TTFT 关键路径上：每个未命中前两层的请求都要等它。走本地
    TCP 环回要经过完整的协议栈——三次握手、Nagle、内核收发缓冲、校验和——
    而这些对同机进程间通信没有任何价值。UDS 绕过整个网络栈，只做一次
    内核内存拷贝。

    This call sits on the TTFT critical path. Local TCP loopback pays for the
    full stack — handshake, Nagle, socket buffers, checksums — none of which
    buys anything between two processes on one machine. A Unix domain socket
    skips the network stack entirely.
    """

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pii.v1.NERService/Analyze',
            pii_dot_v1_dot_ner__pb2.AnalyzeRequest.SerializeToString,
            pii_dot_v1_dot_ner__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pii.v1.NERService/Health',
            pii_dot_v1_dot_ner__pb2.HealthRequest.SerializeToString,
            pii_dot_v1_dot_ner__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
